#!/bin/sh
#
# Script to bring down and delete bridge br0 when QEMU exits
#
# Bring down eth0 and br0
#
sudo ifconfig eth0 down
sudo ifconfig br0 down
#
# Delete the bridge
#
sudo brctl delbr br0
#
# bring up eth0 in "normal" mode
#
sudo ifconfig eth0 -promisc
sudo ifconfig eth0 up
#
# delete the tap device
#
sudo openvpn --rmtun --dev $1
